ORG 1000H
MSJ DB "INGRESE LA CONTRASEÑA:"
ERROR DB  "-CONTRASEÑA INVALIDA-"
CONTRA DB "abcd"
INGRESAR DB ?
BLOCK DB "-BLOQUEADO-"
FINAL DB ?

ORG 2000H
  MOV AX, 0
  MOV BX, 0
  MOV CX, 0
  MOV CX, 0
  MOV CL, 4
  MOV BX, OFFSET MSJ
  MOV AL, OFFSET ERROR - OFFSET MSJ
  INT 7
     MOV BX, OFFSET INGRESAR
LOOP:INT 6
     INC BX
     DEC CL
     JNZ LOOP
     MOV CL, 4
       MOV BX, OFFSET CONTRA
       MOV AX, [BX]
       MOV BX, OFFSET INGRESAR
       CMP [BX], AX
       JZ ERRAR
