ORG 1000H
FIN DB "FIN DEL PROGRAMA"
LLAVE DB "ACTIVADA"
AGUA DB ?

ORG 3000H
PUNTOA: IN AL, PA
        CMP AL, 0FFH
        JNZ OTRO
        MOV AGUA, 1
OTRO:
        RET
        
ORG 3100H
PUNTOB: IN AL, PA
        NOT AL
        OUT PB, AL
        RET
        
ORG 3200H
PUNTOC: IN AL, PA
        AND AL, 10000000B
        JZ MEVOY
        MOV BX, OFFSET LLAVE
        MOV AL, OFFSET AGUA - OFFSET LLAVE
        INT 7
MEVOY:  RET

ORG 2000H
MOV AL, 0
OUT CB, AL
MOV AL, 0FFH
OUT CA, AL
LOOP:CALL PUNTOA
     CALL PUNTOB
     CALL PUNTOC
     CMP AGUA, 1
     JNZ LOOP
MOV BX, OFFSET FIN
MOV AL, OFFSET LLAVE - OFFSET FIN
INT 7
INT 0
END
